name: Deploy Production

on:
    push:
        branches:
            - main

env:
    IMAGE_REPO: ghcr.io/${{ github.repository }}
    SSH_KEY: ${{ secrets.SSH_KEY }}
    SERVER_IP: ${{ secrets.SERVER_IP }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag intaniarun-production
            - name: Docker login using Github Token
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
            - name: Deploy Docker Image
              run: |
                  docker tag intaniarun-production ghcr.io/${{ env.IMAGE_REPO }}/intaniarun-production
                  docker push ghcr.io/${{ env.IMAGE_REPO }}/intaniarun-production
            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H "${{ env.SERVER_IP }}" >> ~/.ssh/known_hosts
            - name: SSH and execute deploy.sh
              run: |
                  ssh -i ~/.ssh/id_rsa ubuntu@"${{env.SERVER_IP}}" "bash ~/deploy.sh"
