name: Deploy Production

on:
    push:
        branches:
            - main

env:
    IMAGE_REPO: ghcr.io/${{ github.repository }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag intaniarun-production
            - name: Docker login using Github Token
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
            - name: Deploy Docker Image
              run: |
                  docker tag intaniarun-production ghcr.io/${{ env.IMAGE_REPO }}/intaniarun-production
                  docker push ghcr.io/${{ env.IMAGE_REPO }}/intaniarun-production